name: Deploy to Amazon EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Select image tag to deploy to EKS"
        required: true

jobs:
  notification-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'There is a deploy for ${{ github.event.inputs.tag }}.\n Need your approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
