name: Deploy to Amazon EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Select image tag to deploy to EKS"
        required: true

jobs:
  - name: Discord notification
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: 'There is a deploy for ${{ github.event.inputs.tag }}.\n Need you approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
