name: Deploy to Amazon EKS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Select image tag to deploy to EKS"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "test"
